# Generated by Django 4.2 on 2024-11-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=60)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stock', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('usuario', models.AutoField(primary_key=True, serialize=False)),
                ('pasword', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
